# Dokploy-Compatible Docker Compose for Redash - ROBUST VERSION
# Optimizado para resolución DNS y orden de inicio en Dokploy

x-redash-service: &redash-service
  image: redash/redash:latest
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy
  environment:
    REDASH_REDIS_URL: "redis://redis:6379/0"
    REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
    REDASH_CELERY_BROKER: "redis://redis:6379/0"
  restart: unless-stopped
  # Agregar configuración de DNS explícita
  dns:
    - 8.8.8.8
    - 1.1.1.1

services:
  # IMPORTANTE: Redis debe iniciar primero
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    # Configuración adicional para estabilidad
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory-policy allkeys-lru

  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  server:
    <<: *redash-service
    command: server
    ports:
      - "${REDASH_EXTERNAL_PORT:-5001}:${REDASH_INTERNAL_PORT:-5000}"
    environment:
      REDASH_WEB_WORKERS: 4
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_CELERY_BROKER: "redis://redis:6379/0"
      REDASH_HOST: "${REDASH_HOST:-http://localhost:${REDASH_EXTERNAL_PORT:-5001}}"
      REDASH_SECRET_KEY: "${REDASH_SECRET_KEY:-change-me}"
      REDASH_COOKIE_SECRET: "${REDASH_COOKIE_SECRET:-change-me}"
      REDASH_WTF_CSRF_SECRET_KEY: "${REDASH_WTF_CSRF_SECRET_KEY:-change-me}"
      REDASH_LOG_LEVEL: "INFO"
      REDASH_ENFORCE_CSRF: "true"
      # Variables adicionales para conexión robusta
      REDASH_REDIS_SOCKET_TIMEOUT: "20"
      REDASH_REDIS_CONNECTION_POOL_MAX_CONNECTIONS: "20"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${REDASH_INTERNAL_PORT:-5000}/ping",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s # Más tiempo para que Redis/Postgres estén listos
    # Configuración de reinicio más agresiva
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_CELERY_BROKER: "redis://redis:6379/0"
      REDASH_HOST: "${REDASH_HOST:-http://localhost:${REDASH_EXTERNAL_PORT:-5001}}"
      REDASH_SECRET_KEY: "${REDASH_SECRET_KEY:-change-me}"
      REDASH_COOKIE_SECRET: "${REDASH_COOKIE_SECRET:-change-me}"
      REDASH_WTF_CSRF_SECRET_KEY: "${REDASH_WTF_CSRF_SECRET_KEY:-change-me}"
      REDASH_REDIS_SOCKET_TIMEOUT: "20"

  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_CELERY_BROKER: "redis://redis:6379/0"
      REDASH_HOST: "${REDASH_HOST:-http://localhost:${REDASH_EXTERNAL_PORT:-5001}}"
      REDASH_SECRET_KEY: "${REDASH_SECRET_KEY:-change-me}"
      REDASH_COOKIE_SECRET: "${REDASH_COOKIE_SECRET:-change-me}"
      REDASH_WTF_CSRF_SECRET_KEY: "${REDASH_WTF_CSRF_SECRET_KEY:-change-me}"
      REDASH_REDIS_SOCKET_TIMEOUT: "20"

  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_CELERY_BROKER: "redis://redis:6379/0"
      REDASH_HOST: "${REDASH_HOST:-http://localhost:${REDASH_EXTERNAL_PORT:-5001}}"
      REDASH_SECRET_KEY: "${REDASH_SECRET_KEY:-change-me}"
      REDASH_COOKIE_SECRET: "${REDASH_COOKIE_SECRET:-change-me}"
      REDASH_WTF_CSRF_SECRET_KEY: "${REDASH_WTF_CSRF_SECRET_KEY:-change-me}"
      REDASH_REDIS_SOCKET_TIMEOUT: "20"

volumes:
  postgres_data:
  redis_data:
